       or new.created_at is distinct from old.created_at then
      raise exception 'Protected profile fields may only be changed by a moderator';
    end if;
    if new.status is distinct from old.status then
      if old.user_id is distinct from caller then
        raise exception 'Profile status change is not allowed';
      end if;
      if old.status='suspended' then
        raise exception 'A suspended profile may only be restored by a moderator';
      end if;
      if not (
        (old.status='active' and new.status='removed')
        or (old.status='removed' and new.status='active')
      ) then
        raise exception 'Profile status change is not allowed';
      end if;
    end if;
  end if;
  return new;
end;
$function$;
create or replace function public.enforce_field_feed_insert_rate_limits()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public
as $function$
declare
  recent_count integer;
  daily_count integer;
  caller uuid := auth.uid();
begin
  if caller is null then
    raise exception 'Authentication required';
  end if;
  if not public.brinesearch_user_email_verified(caller) then
    raise exception 'Verify your email before posting';
  end if;
  if tg_table_name='field_posts' then
    select count(*) into recent_count from public.field_posts
      where author_id=caller and created_at>now()-interval '10 minutes';
    select count(*) into daily_count from public.field_posts
      where author_id=caller and created_at>now()-interval '24 hours';
    if recent_count>=3 or daily_count>=12 then
      raise exception 'Post limit reached. Try again later.';
    end if;
  elsif tg_table_name='field_comments' then
    select count(*) into recent_count from public.field_comments
      where author_id=caller and created_at>now()-interval '10 minutes';
    select count(*) into daily_count from public.field_comments
      where author_id=caller and created_at>now()-interval '24 hours';
    if recent_count>=12 or daily_count>=60 then
      raise exception 'Comment limit reached. Try again later.';
    end if;
  elsif tg_table_name='field_reports' then
    select count(*) into recent_count from public.field_reports
      where reporter_id=caller and created_at>now()-interval '1 hour';
    select count(*) into daily_count from public.field_reports
      where reporter_id=caller and created_at>now()-interval '24 hours';
    if recent_count>=3 or daily_count>=10 then
      raise exception 'Report limit reached. Try again later.';
    end if;
  elsif tg_table_name='field_post_votes' then
    select count(*) into recent_count from public.field_post_votes
      where user_id=caller and created_at>now()-interval '10 minutes';
    select count(*) into daily_count from public.field_post_votes
      where user_id=caller and created_at>now()-interval '24 hours';
    if recent_count>=30 or daily_count>=200 then
      raise exception 'Vote limit reached. Try again later.';
    end if;
  end if;
  return new;
end;
$function$;
create table if not exists private_verification.public_submission_rate_events (
  id bigint generated by default as identity primary key,
  request_id uuid not null unique,
  ip_hash text not null check (ip_hash ~ '^[0-9a-f]{64}$'),
  identity_hash text not null check (identity_hash ~ '^[0-9a-f]{64}$'),
  company text,
  state text,
  pad_name text,
  captcha_hostname text,
  dry_run boolean not null default false,
  created_at timestamptz not null default now()
);
create index if not exists public_submission_rate_events_ip_created_idx
  on private_verification.public_submission_rate_events(ip_hash,created_at desc);
create index if not exists public_submission_rate_events_identity_created_idx
  on private_verification.public_submission_rate_events(identity_hash,created_at desc);
alter table private_verification.public_submission_rate_events enable row level security;
revoke all on private_verification.public_submission_rate_events from public,anon,authenticated;
create or replace function public.submit_pad_server(
  p_payload jsonb,
  p_ip_hash text,
  p_identity_hash text,
  p_request_id uuid,
  p_captcha_hostname text default null,
  p_dry_run boolean default false
)
returns uuid
language plpgsql
security definer
set search_path = pg_catalog, public, private_verification
as $function$
declare
  jwt_role text;
  v_id uuid;
  v_entries jsonb := coalesce(p_payload->'p_well_entries','[]'::jsonb);
  v_company text := btrim(coalesce(p_payload->>'p_company',''));
  v_state text := upper(btrim(coalesce(p_payload->>'p_state','')));
  v_name text := btrim(coalesce(p_payload->>'p_pad_name',''));
begin
  jwt_role := coalesce(
    nullif(current_setting('request.jwt.claim.role',true),''),
    nullif(current_setting('request.jwt.claims',true),'')::jsonb->>'role'
  );
  if jwt_role is distinct from 'service_role' then
    raise exception 'Service role required';
  end if;
  if p_payload is null or jsonb_typeof(p_payload)<>'object' then
    raise exception 'invalid_payload';
  end if;
  if octet_length(p_payload::text)>65536 then
    raise exception 'payload_too_large';
  end if;
  if p_ip_hash is null or p_ip_hash !~ '^[0-9a-f]{64}$' then
    raise exception 'invalid_ip_hash';
  end if;
  if p_identity_hash is null or p_identity_hash !~ '^[0-9a-f]{64}$' then
    raise exception 'invalid_identity_hash';
  end if;
  if p_request_id is null then
    raise exception 'invalid_request_id';
  end if;
  if jsonb_typeof(v_entries)<>'array' or jsonb_array_length(v_entries)>25 then
    raise exception 'invalid_well_entries';
  end if;
  if char_length(coalesce(p_payload->>'p_address',''))>500
     or char_length(coalesce(p_payload->>'p_county',''))>120
     or char_length(coalesce(p_payload->>'p_township',''))>120
     or char_length(coalesce(p_payload->>'p_structured_road_sequence',''))>6000
     or char_length(coalesce(p_payload->>'p_written_directions',''))>12000
     or char_length(coalesce(p_payload->>'p_notes',''))>5000
     or char_length(coalesce(p_payload->>'p_submitter_contact',''))>254
     or char_length(coalesce(p_payload->>'p_source_page',''))>1000 then
    raise exception 'submission_field_too_long';
  end if;
  if (
    select count(*)
    from private_verification.public_submission_rate_events e
    where e.ip_hash=p_ip_hash
      and e.created_at>now()-interval '1 hour'
  )>=5 or (
    select count(*)
