-- BrineSearch V17.3.18
-- Preserve the pad-specific backward/centerline measurements as first-class
-- per-road segments.  Rejected measurements are retained for audit but are
-- never exposed to the driver UI as usable mileage.

create table if not exists public.brinesearch_pad_measured_road_segments (
  id bigint generated by default as identity primary key,
  pad_id uuid not null references public.pads(id) on delete cascade,
  legacy_id text,
  segment_order integer not null,
  road_key text not null,
  measured_miles numeric not null,
  display_distance text not null,
  measurement_method text not null,
  confidence numeric,
  connector_gap_miles numeric,
  usable boolean not null default false,
  rejection_reason text,
  source_measurement_at timestamptz,
  source_evidence jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (pad_id, segment_order)
);

create index if not exists brinesearch_pad_measured_road_segments_pad_road_idx
  on public.brinesearch_pad_measured_road_segments(pad_id, road_key);

alter table public.brinesearch_pad_measured_road_segments enable row level security;
revoke all on table public.brinesearch_pad_measured_road_segments from anon, authenticated;

create or replace function public.brinesearch_sync_pad_measured_road_segments(p_pad_id uuid)
returns integer
language plpgsql
security definer
set search_path=public,pg_temp
as $$
declare
  inserted_count integer := 0;
begin
  delete from public.brinesearch_pad_measured_road_segments where pad_id=p_pad_id;

  insert into public.brinesearch_pad_measured_road_segments(
    pad_id,legacy_id,segment_order,road_key,measured_miles,display_distance,
    measurement_method,confidence,connector_gap_miles,usable,rejection_reason,
    source_measurement_at,source_evidence,updated_at
  )
  select
    m.pad_id,
    m.legacy_id,
    s.ordinality::integer,
    upper(btrim(s.segment->>'road')),
    (s.segment->>'miles')::numeric,
    '≈ ' || trim(to_char((s.segment->>'miles')::numeric,'FM999990.00')) || ' mi',
    m.method,
    m.confidence,
    m.connector_gap_miles,
    (
      m.method='official_centerline_pad_specific'
      and coalesce(m.confidence,0) >= 0.80
      and coalesce(m.connector_gap_miles,0) <= 1.0
      and coalesce(m.connector_gap_miles,0) / nullif(m.measured_miles,0) <= 0.20
    ) as usable,
    case
      when m.method<>'official_centerline_pad_specific' then 'measurement withheld by prior mileage audit'
      when coalesce(m.confidence,0) < 0.80 then 'measurement confidence below publish threshold'
      when coalesce(m.connector_gap_miles,0) > 1.0 then 'unmapped connector exceeds 1 mile'
      when coalesce(m.connector_gap_miles,0) / nullif(m.measured_miles,0) > 0.20 then 'unmapped connector exceeds 20 percent of route'
      else null
    end,
    m.measured_at,
    jsonb_build_object(
      'source','brinesearch_pad_mileage_measurements.evidence.segments',
      'segment',s.segment,
      'pad_total_miles',m.measured_miles,
      'connector_gap_miles',m.connector_gap_miles,
      'measurement_evidence',m.evidence
    ),
    now()
  from public.brinesearch_pad_mileage_measurements m
  cross join lateral jsonb_array_elements(coalesce(m.evidence->'segments','[]'::jsonb)) with ordinality as s(segment,ordinality)
  where m.pad_id=p_pad_id
    and nullif(btrim(s.segment->>'road'),'') is not null
    and nullif(btrim(s.segment->>'miles'),'') is not null
    and (s.segment->>'miles')::numeric > 0;

  get diagnostics inserted_count=row_count;
  return inserted_count;
end
$$;
revoke all on function public.brinesearch_sync_pad_measured_road_segments(uuid) from public,anon,authenticated;

-- Seed every measurement currently preserved in the database. This keeps both
-- accepted and rejected historical work, with a usable flag enforcing the
-- prior no-guess / connector-gap audit.
do $$
declare r record;
begin
  for r in select pad_id from public.brinesearch_pad_mileage_measurements loop
    perform public.brinesearch_sync_pad_measured_road_segments(r.pad_id);
  end loop;
end
$$;

create or replace function public.brinesearch_pad_measured_road_segments(p_pad_id uuid)
returns table(
  segment_order integer,
  road_key text,
  distance_miles numeric,
  distance_label text,
  confidence numeric,
  measurement_method text
)
language sql
stable
security definer
set search_path=public,pg_temp
as $$
  select s.segment_order,s.road_key,s.measured_miles,s.display_distance,
         s.confidence,s.measurement_method
  from public.brinesearch_pad_measured_road_segments s
  where s.pad_id=p_pad_id and s.usable
  order by s.segment_order
$$;
revoke all on function public.brinesearch_pad_measured_road_segments(uuid) from public,anon,authenticated;
grant execute on function public.brinesearch_pad_measured_road_segments(uuid) to anon,authenticated;

create or replace function public.brinesearch_pad_mileage_measurement_sync_trigger()
returns trigger
language plpgsql
security definer
set search_path=public,pg_temp
as $$
begin
  perform public.brinesearch_sync_pad_measured_road_segments(new.pad_id);
  return new;
end
$$;
revoke all on function public.brinesearch_pad_mileage_measurement_sync_trigger() from public,anon,authenticated;

drop trigger if exists brinesearch_pad_mileage_measurement_sync on public.brinesearch_pad_mileage_measurements;
create trigger brinesearch_pad_mileage_measurement_sync
after insert or update of measured_miles,display_miles,method,confidence,connector_gap_miles,route_keys,evidence,measured_at
on public.brinesearch_pad_mileage_measurements
for each row execute function public.brinesearch_pad_mileage_measurement_sync_trigger();
