(() => {
  const CACHE_KEY = "brinesearch_weather_v2";
  const CONSENT_KEY = "brinesearch.weatherLocationConsent.v1";
  const CACHE_MS = 20 * 60 * 1000;
  const weatherInfo = (code, isDay = 1) => {
    const table=[[[0],isDay?"☀️":"🌙","Clear"],[[1],isDay?"🌤️":"🌙","Mostly clear"],[[2],"⛅","Partly cloudy"],[[3],"☁️","Cloudy"],[[45,48],"🌫️","Fog"],[[51,53,55,56,57],"🌦️","Drizzle"],[[61,63,65,66,67,80,81,82],"🌧️","Rain"],[[71,73,75,77,85,86],"🌨️","Snow"],[[95,96,99],"⛈️","Thunderstorms"]];
    return table.find(([codes])=>codes.includes(Number(code)))?.slice(1)||["🌤️","Weather"];
  };
  const safeJson=async r=>{if(!r.ok) throw new Error(`Weather request failed (${r.status})`);return r.json();};
  const getPlace=async(lat,lon)=>{try{const u=`https://api.bigdatacloud.net/data/reverse-geocode-client?latitude=${encodeURIComponent(lat)}&longitude=${encodeURIComponent(lon)}&localityLanguage=en`;const d=await fetch(u,{cache:"no-store"}).then(safeJson);return d.city||d.locality||d.principalSubdivision||"Local weather";}catch{return "Local weather";}};
  const getForecast=async(lat,lon)=>{const q=new URLSearchParams({latitude:String(lat),longitude:String(lon),current:"temperature_2m,apparent_temperature,is_day,weather_code,wind_speed_10m,wind_direction_10m",hourly:"temperature_2m,apparent_temperature,precipitation_probability,weather_code,is_day,wind_speed_10m",temperature_unit:"fahrenheit",wind_speed_unit:"mph",precipitation_unit:"inch",timezone:"auto",forecast_days:"2"});return fetch(`https://api.open-meteo.com/v1/forecast?${q}`,{cache:"no-store"}).then(safeJson);};
  const getPosition=()=>new Promise((resolve,reject)=>{if(!navigator.geolocation)return reject(new Error("Location is not supported"));navigator.geolocation.getCurrentPosition(resolve,reject,{enableHighAccuracy:false,timeout:12000,maximumAge:15*60*1000});});
  const tile=document.createElement("button");tile.type="button";tile.className="weather-header-tile";tile.setAttribute("aria-label","Open 12-hour local weather forecast");tile.innerHTML=`<span class="weather-header-icon">🌤️</span><span class="weather-header-copy"><strong class="weather-header-temp">--°</strong><small class="weather-header-place">Weather</small></span>`;
  const brand=document.querySelector(".header-row .brand");if(brand)brand.insertAdjacentElement("afterend",tile);
  const modal=document.createElement("div");modal.className="weather-modal";modal.setAttribute("role","dialog");modal.setAttribute("aria-modal","true");modal.setAttribute("aria-label","Twelve-hour weather forecast");document.body.appendChild(modal);
  let weatherState=null;
  const consentSheet=()=>{modal.querySelector(".weather-sheet")?.remove();modal.innerHTML=`<section class="weather-sheet"><div class="weather-sheet-head"><div><h2>Local weather</h2><p>12-hour forecast for your current area</p></div><button class="icon-btn" type="button" data-weather-close aria-label="Close forecast"><span class="fm-icon fm-close"></span></button></div><div class="weather-privacy"><strong>Location privacy</strong><br>BrineSearch uses your approximate location only to request local weather. Your location is not posted to the Field Feed or attached to your profile.</div><div class="weather-sheet-actions"><button class="btn primary" type="button" data-weather-consent>Use my location</button><button class="btn ghost" type="button" data-weather-close>Not now</button></div></section>`;};
  const updateTile=state=>{if(!state)return;const[icon]=weatherInfo(state.forecast.current.weather_code,state.forecast.current.is_day);tile.classList.remove("loading");tile.querySelector(".weather-header-icon").textContent=icon;tile.querySelector(".weather-header-temp").textContent=`${Math.round(state.forecast.current.temperature_2m)}°`;tile.querySelector(".weather-header-place").textContent=state.place;};
  const renderSheet=state=>{const f=state.forecast,c=f.current,[icon,condition]=weatherInfo(c.weather_code,c.is_day);const now=Date.now();const hours=(f.hourly?.time||[]).map((t,i)=>({t:new Date(t),i})).filter(x=>x.t.getTime()>=now-30*60*1000).slice(0,12).map(({t,i})=>{const[hi,hc]=weatherInfo(f.hourly.weather_code?.[i],f.hourly.is_day?.[i]);const rain=f.hourly.precipitation_probability?.[i];return `<div class="weather-hour"><strong class="weather-hour-time">${t.toLocaleTimeString([],{hour:"numeric"})}</strong><span class="weather-hour-icon">${hi}</span><span class="weather-hour-condition">${hc}${Number.isFinite(rain)?` · ${rain}% rain`:""}<br><small>Wind ${Math.round(f.hourly.wind_speed_10m?.[i]||0)} mph</small></span><span class="weather-hour-temp">${Math.round(f.hourly.temperature_2m?.[i])}°</span></div>`;}).join("");modal.innerHTML=`<section class="weather-sheet"><div class="weather-sheet-head"><div><h2>${state.place}</h2><p>Next 12 hours</p></div><button class="icon-btn" type="button" data-weather-close aria-label="Close forecast"><span class="fm-icon fm-close"></span></button></div><div class="weather-current-card"><div class="weather-current-icon">${icon}</div><div><div class="weather-current-temp">${Math.round(c.temperature_2m)}°</div><div class="weather-current-condition">${condition}</div><div class="weather-current-meta">Feels like ${Math.round(c.apparent_temperature)}° · Wind ${Math.round(c.wind_speed_10m)} mph</div></div></div><h3 class="weather-forecast-title">12-Hour Forecast</h3><div class="weather-hour-list">${hours}</div><div class="weather-sheet-actions"><button class="btn secondary" type="button" data-weather-refresh>Refresh location</button><button class="btn ghost" type="button" data-weather-close>Close</button></div></section>`;};
  const showError=message=>{tile.classList.remove("loading");modal.innerHTML=`<section class="weather-sheet"><div class="weather-sheet-head"><div><h2>Local weather</h2><p>Weather unavailable</p></div><button class="icon-btn" type="button" data-weather-close><span class="fm-icon fm-close"></span></button></div><div class="weather-error">${message}</div><div class="weather-sheet-actions"><button class="btn primary" type="button" data-weather-refresh>Try again</button><button class="btn ghost" type="button" data-weather-close>Close</button></div></section>`;};
  const loadWeather=async(force=false)=>{tile.classList.add("loading");if(!force){try{const cached=JSON.parse(localStorage.getItem(CACHE_KEY)||"null");if(cached?.savedAt&&Date.now()-cached.savedAt<CACHE_MS){weatherState=cached;updateTile(cached);return cached;}}catch{}}const position=await getPosition();const lat=position.coords.latitude,lon=position.coords.longitude;const[forecast,place]=await Promise.all([getForecast(lat,lon),getPlace(lat,lon)]);weatherState={savedAt:Date.now(),lat,lon,place,forecast};localStorage.setItem(CACHE_KEY,JSON.stringify(weatherState));updateTile(weatherState);return weatherState;};
  tile.addEventListener("click",async()=>{modal.classList.add("open");if(!localStorage.getItem(CONSENT_KEY)&&!weatherState){consentSheet();return;}try{const state=weatherState||await loadWeather(false);renderSheet(state);}catch(e){showError(e?.code===1?"Location permission is turned off. Allow location access in Safari settings, then try again.":"Weather could not load right now. Check your connection and try again.");}});
  modal.addEventListener("click",async e=>{if(e.target===modal||e.target.closest("[data-weather-close]"))modal.classList.remove("open");if(e.target.closest("[data-weather-consent]")){localStorage.setItem(CONSENT_KEY,"yes");try{renderSheet(await loadWeather(true));}catch(err){showError(err?.code===1?"Location permission is turned off. Allow it in Safari settings, then try again.":"Weather could not load right now.");}}if(e.target.closest("[data-weather-refresh]")){try{renderSheet(await loadWeather(true));}catch{}}});
  try{const cached=JSON.parse(localStorage.getItem(CACHE_KEY)||"null");if(cached?.savedAt){weatherState=cached;updateTile(cached);}}catch{}
})();
